# frontend/app.py
import streamlit as st
import requests
import uuid
import time
import os
from ui_components import (
    render_decision_card, 
    render_tool_results, 
    render_evidence_panel, 
    render_guardrails_status, 
    render_agent_trace
)

# Use environment variable for API URL with localhost fallback for development
API_URL = os.getenv("API_URL", "http://localhost:8000")

# --- Page Config ---
st.set_page_config(page_title="Loan Assistant", page_icon="🏦", layout="wide")
st.title("🏦 Enterprise Loan & Credit Assistant")

# --- Session State Initialization ---
if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())
if "messages" not in st.session_state:
    st.session_state.messages = []
if "collected_inputs" not in st.session_state:
    st.session_state.collected_inputs = {}

# --- Helper: Typewriter Effect (Phase 4) ---
def stream_text(text: str):
    for word in text.split(" "):
        yield word + " "
        time.sleep(0.04)

# --- Sidebar Configuration ---
with st.sidebar:
    st.header("Applicant Info")
    if st.session_state.collected_inputs:
        for key, value in st.session_state.collected_inputs.items():
            display_val = str(value) if value is not None else "Pending..."
            st.text_input(key.replace("_", " ").title(), value=display_val, disabled=True)
    else:
        st.info("No data collected yet. Start chatting!")
        
    st.divider()
    
    st.header("Upload Documents")
    uploaded_file = st.file_uploader("Upload Policy or Financial Docs", type=["txt"])
    if uploaded_file:
        if st.button("Process Document"):
            with st.spinner("Ingesting into Vector Database..."):
                try:
                    files = {"file": (uploaded_file.name, uploaded_file.getvalue(), "text/plain")}
                    upload_res = requests.post(f"{API_URL}/upload", files=files)
                    if upload_res.status_code == 200:
                        data = upload_res.json()
                        # RESTORED: Full success message with chunk counts
                        st.success(f"✅ Successfully learned '{data['filename']}' ({data['chunks_added']} chunks added!)")
                    else:
                        st.error("Upload failed.")
                except Exception as e:
                    st.error(f"Error connecting to backend: {e}")
        
    st.divider()
    
    st.header("🛠️ RAG Debugger")
    debug_query = st.text_input("Test Retrieval Query")
    if st.button("Run RAG Query"):
        try:
            res = requests.post(f"{API_URL}/rag/query", json={"query": debug_query, "k": 3})
            if res.status_code == 200:
                st.json(res.json())
        except Exception:
            st.error("Backend unreachable.")

    st.divider()
    if st.button("Clear Session (Reset)"):
        st.session_state.clear()
        st.rerun()

# --- Main Chat Interface ---
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg["role"] == "assistant" and "metadata" in msg:
            meta = msg["metadata"]
            render_agent_trace(meta.get("agent_trace", []))
            render_guardrails_status(meta.get("guardrails"))
            render_decision_card(meta.get("decision"))
            render_tool_results(meta.get("tool_results"))
            render_evidence_panel(meta.get("rag"))
            
            # RESTORED: Offer Letter Download
            decision_data = meta.get("decision", {})
            if decision_data.get("status") == "APPROVE":
                offer_letter = f"OFFICIAL LOAN OFFER LETTER\n\n{msg['content']}\n\nGenerated by Enterprise Loan Assistant."
                st.download_button(
                    label="📄 Download Official Offer Letter",
                    data=offer_letter,
                    file_name=f"Loan_Offer_{st.session_state.session_id[:8]}.txt",
                    mime="text/plain", type="primary"
                )
            
            # RESTORED: Latency metrics in history
            if "latency_ms" in meta and meta["latency_ms"]:
                st.caption(f"⏱️ Latency: LLM `{meta['latency_ms'].get('llm')}ms` | End-to-End `{meta['latency_ms'].get('end_to_end')}ms`")

# Chat Input Box
if prompt := st.chat_input("Ask about policies or apply for a loan..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("🧠 Agentic Orchestrator Thinking..."):
            try:
                response = requests.post(f"{API_URL}/chat", json={
                    "session_id": st.session_state.session_id,
                    "message": prompt,
                    "metadata": {"channel": "streamlit"} # RESTORED: Channel metadata
                })
                
                if response.status_code == 200:
                    data = response.json()
                    reply = data.get("reply", "")
                    st.session_state.collected_inputs = data.get("collected_inputs", {})
                    
                    # EFFECT: Stream the text response
                    st.write_stream(stream_text(reply))
                    
                    # Display analytical components
                    render_agent_trace(data.get("agent_trace", []))
                    render_guardrails_status(data.get("guardrails"))
                    render_decision_card(data.get("decision"))
                    render_tool_results(data.get("tool_results"))
                    render_evidence_panel(data.get("rag"))

                    # Download Offer Letter (New Response)
                    if data.get("decision", {}).get("status") == "APPROVE":
                        offer_letter = f"OFFICIAL LOAN OFFER LETTER\n\n{reply}\n\nGenerated by Enterprise Loan Assistant."
                        st.download_button(
                            label="📄 Download Official Offer Letter",
                            data=offer_letter,
                            file_name=f"Loan_Offer_{st.session_state.session_id[:8]}.txt",
                            mime="text/plain", type="primary"
                        )
                    
                    # RESTORED: Latency metrics for new response
                    if "latency_ms" in data:
                        st.caption(f"⏱️ Latency: LLM `{data['latency_ms'].get('llm')}ms` | End-to-End `{data['latency_ms'].get('end_to_end')}ms`")
                    
                    # Save with ALL metadata fields
                    st.session_state.messages.append({
                        "role": "assistant", "content": reply,
                        "metadata": {
                            "decision": data.get("decision"),
                            "tool_results": data.get("tool_results"),
                            "rag": data.get("rag"),
                            "guardrails": data.get("guardrails"),
                            "agent_trace": data.get("agent_trace"),
                            "latency_ms": data.get("latency_ms") # RESTORED
                        }
                    })
                    st.rerun()
                else:
                    st.error(f"Backend Error: {response.status_code}")
            except Exception as e:
                st.error(f"🚨 Connection lost: {e}")
